//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentenVolgSysteem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Benodigdheden> Benodigdheden { get; set; }
        public virtual DbSet<Certificeringen> Certificeringen { get; set; }
        public virtual DbSet<Curricula> Curricula { get; set; }
        public virtual DbSet<CurriculumTemplates> CurriculumTemplates { get; set; }
        public virtual DbSet<CurriculumTopics> CurriculumTopics { get; set; }
        public virtual DbSet<Niveaus> Niveaus { get; set; }
        public virtual DbSet<PercipioLinks> PercipioLinks { get; set; }
        public virtual DbSet<Studenten> Studenten { get; set; }
        public virtual DbSet<Tags> Tags { get; set; }
        public virtual DbSet<Tijdsduren> Tijdsduren { get; set; }
        public virtual DbSet<Topics> Topics { get; set; }
        public virtual DbSet<Werkvormen> Werkvormen { get; set; }
    }
}
